controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

registration:
    path: /register
    controller: App\Controller\RegistrationController::register

answer_question:
    path: /answer/{id}
    controller: App\Controller\AppController::answerQuestion

